---

- include_tasks: tasks/redhat/install.yml
  when: ansible_os_family == 'RedHat'
  tags: logstash

- include_tasks: tasks/debian/install.yml
  when: ansible_os_family == 'Debian'
  tags: logstash

- include_tasks: configure.yml
  tags:
    - logstash
    - configure
