---

- include_tasks: tasks/redhat/install.yml
  when: ansible_os_family == 'RedHat'
  tags: elasticsearch

- include_tasks: tasks/debian/install.yml
  when: ansible_os_family == 'Debian'
  tags: elasticsearch


