---

# tasks file for vm_template
- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: user password
  user:
    name: root
    password: "{{ vm_template_password }}"

- name: set http proxy to bashrc
  lineinfile:
    path: /root/.bashrc
    regexp: '^http_proxy='
    line: "http_proxy={{ proxy_env.http_proxy }}"
  when: proxy_env.http_proxy is defined

- name: set https proxy to bashrc
  lineinfile:
    path: /root/.bashrc
    regexp: '^https_proxy='
    line: "https_proxy={{ proxy_env.https_proxy }}"
  when: proxy_env.https_proxy is defined

- include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'
