---

#- hosts: all
#  gather_facts: no
#  pre_tasks:
#    - include_vars:
#        file: group_vars/vault.yml
#  tasks:
#    - debug:
#        msg: "{{ es_cluster_name }} - {{ vm_template_password }}"

- hosts: roles/esmaster
  gather_facts: yes
  pre_tasks:
  - set_fact:
      es_master_nodes: "{{ es_cluster_master_nodes | es_ip_list(hostvars) }}"
    tags: always
    changed_when: False
  roles:
  - esmaster

- hosts: roles/esdata
  gather_facts: yes
  pre_tasks:
  - set_fact:
      es_master_nodes: "{{ es_cluster_master_nodes | es_ip_list(hostvars) }}"
    tags: always
    changed_when: False
  roles:
  - esdata

- hosts: roles/escordinator
  gather_facts: yes
  pre_tasks:
  - set_fact:
      es_master_nodes: "{{ es_cluster_master_nodes | es_ip_list(hostvars) }}"
    tags: always
    changed_when: False
  roles:
  - escordinator


