---
# handlers file for logstash
- name: restart logstash
  systemd:
    name: logstash
    state: started
    enabled: yes
    daemon_reload: yes

# reload conf
- name: reload logstash
  systemd:
    name: logstash
    state: reload
    enabled: yes
    daemon_reload: yes

