---
zabbix_agent_host_metadata: elasticsearch
cluster_group: "{{ (group_names | select('match', '^clusters/') | list)[0] }}"
es_cluster_nodes: "{{ groups[cluster_group] }}"
es_cluster_master_nodes: "{{ es_cluster_nodes | intersect(groups['roles/esmaster']) }}"
es_cluster_data_nodes: "{{ es_cluster_nodes | intersect(groups['roles/esdata']) }}"
es_jvm_Xms: "{{ host_es_min_memory | default('512m') }}"
es_jvm_Xmx: "{{ host_es_max_memory | default('512m') }}"

