---

topics:
  topic.1:
    number_of_partitions: 3
    pipeline_workers: 8 # if undefined this valu will be calculated to be `number of vcpus / number of piplines in same logstash host`
    pipeline_batch_size: 300 # if undefined default value is 125
    pipeline_batch_delay: 100 # ms. default value is 50
    pipeline_conf_file: esxi.conf
    pipeline_conf_template: vmware_product_syslog.conf
    pipeline_grok_parser: "<%{POSINT:syslog_pri}>%{TIMESTAMP_ISO8601:timestamp} %{SYSLOGHOST:hostname} %{SYSLOGPROG}: %{GREEDYDATA:syslog_message}"
    pipeline_index_prefix: test
    pipeline_index_template: esxi_syslog
    beats_input_syslog_host: 0.0.0.0:10514

  topic.2:
    number_of_partitions: 3
    # pipeline_workers: 8
    pipeline_batch_size: 300
    pipeline_batch_delay: 100
    pipeline_conf_file: sample.conf
    pipeline_conf_template: sample.conf

  topic.3:
    number_of_partitions: 3
    pipeline_batch_size: 200
    pipeline_batch_delay: 100
    pipeline_conf_file: esxi_3.conf
    pipeline_conf_template: vmware_product_syslog.conf
    pipeline_grok_parser: "<%{POSINT:syslog_pri}>%{TIMESTAMP_ISO8601:timestamp} %{SYSLOGHOST:hostname} %{SYSLOGPROG}: %{GREEDYDATA:syslog_message}"
    pipeline_index_prefix: test
    pipeline_index_template: esxi_syslog
    additional_fields:
      cellname: cell-1
