---

- name: install pgp key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  environment: "{{ proxy_env }}"

- name: install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
  environment: "{{ proxy_env }}"

- name: add kibana 6.x apt repository
  shell: echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list
  environment: "{{ proxy_env }}"

- name: install kibana
  apt:
    name: kibana={{ kibana_version | default('6.3.0') }}
    state: present
    update_cache: yes
  notify: start kibana
  environment: "{{ proxy_env }}"

