---
# tasks file for heartbeat
- include_tasks: tasks/redhat/configure.yml
  when: ansible_os_family == 'RedHat'
  tags: elasticsearch

- include_tasks: tasks/debian/configure.yml
  when: ansible_os_family == 'Debian'
  tags: elasticsearch

