---

# tasks file for zabbix_agent
# you can check your os family, ansible_distribution ... and so on by `ansible -m setup hostname`

- include_tasks: redHat.yml
  when: ansible_os_family == 'RedHat'
  tags: zabbix_agent
#  Redhat family include CentOS

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'
  tags: zabbix_agent
# Debian include Ubuntu
#
#- include_tasks: ubuntu.yml
#  when: ansible_distribution == 'Ubuntu'

- name: create /etc/zabbix/zabbix_agentd.conf.d directory
  file:
    path: /etc/zabbix/zabbix_agentd.conf.d
    state: directory
  tags: zabbix_agent

- name: configure zabbix-agent
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  tags:
  - configure
  notify:
  - restart zabbix
  tags: zabbix_agent

- name: start zabbix-agent
  systemd:
    name: zabbix-agent
    state: started
    enabled: yes
    daemon_reload: yes
  check_mode: no
  tags: zabbix_agent
