---

- name: install zabbix 3 repository
  yum:
    name: http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm
    state: present
  tags:
  - install

- name: install zabbix-agent
  yum:
    name: zabbix-agent
    state: present
  update_cache: yes
  tags:
  - install

- name: start zabbix-agent
  systemd:
    name: zabbix-agent
    state: started
    enabled: yes
    daemon_reload: yes


