---
#- name: install zabbix 3 yum repositoy
#  shell: http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm
#    state: absent
#  environemtn: "{{ proxy_env }}"
#  tags:
#  - install

- name: install zabbix 3 yum repo
  shell: rpm --force -ivh http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-release-3.2-1.el7.noarch.rpm

- name: install zabbix-agent
  yum:
    name: zabbix-agent
    state: present
    update_cache: yes
  environemtn: "{{ proxy_env }}"
  tags:
  - install

- name: start zabbix-agent
  systemd:
    name: zabbix-agent
    state: started
    enabled: yes
    daemon_reload: yes

