---
# tasks file for elasticsearch

- include_tasks: tasks/redhat/install.yml
  when: ansible_os_family == 'RedHat'
  tags: elasticsearch

- include_tasks: tasks/debian/install.yml
  when: ansible_os_family == 'Debian'
  tags: elasticsearch

- include_tasks: configure.yml
  tags:
    - elasticsearch
    - configure
