---

- name: install gpg-key
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  environment: "{{ proxy_env }}"

- name: add elastic 6.x yum repository
  template:
    src: etc/yum.repos.d/elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: "install {{ beat_package }} 6"
  yum:
    name: "{{ beat_package }}-{{ beat_version | default('6.3.0') }}"
    state: present
  environment: "{{ proxy_env }}"
