---
# tasks file for escurator
- include_tasks: tasks/redhat/install.yml
  when: ansible_os_family == 'RedHat'
  tags: escurator

- include_tasks: tasks/debian/install.yml
  when: ansible_os_family == 'Debian'
  tags: escurator

- include_tasks: configure.yml
  tags:
    - escurator
    - configure
